import { FaTimes } from "react-icons/fa";
import { wizardStyles as styles } from "@/shared/components/wizard/wizardStyles";
import { useWizardController } from "../hooks/useWizardController";
import StrategyChatWidget from "@/features/strategy/components/StrategyChatWidget";
import ConnectPage from "@/features/connect/pages/ConnectPage";
import { ConnectStepView } from "@/features/connect/components/ConnectStepView";
import DiscoveryPage from "@/features/discovery/pages/DiscoveryPage";
import { DiscoveryStepView } from "@/features/discovery/components/DiscoveryStepView";
import StrategyPage from "@/features/strategy/pages/StrategyPage";
import { StrategyStepView } from "@/features/strategy/components/StrategyStepView";
import ModernizationPage from "@/features/modernization/pages/ModernizationPage";
import { ModernizationStepView } from "@/features/modernization/components/ModernizationStepView";
import ResultPage from "@/features/result/pages/ResultPage";
import { MigrationAnimationView } from "@/features/result/components/MigrationAnimationView";
import { MigrationProgressView } from "@/features/result/components/MigrationProgressView";
import { ResultReportView } from "@/features/result/components/ResultReportView";
import "./MigrationWizardPage.css";

export default function MigrationWizardPage() {
  const {
    step,
    setStep,
    error,
    setError,
    selectedRepo,
    setSelectedRepo,
    setRepoUrl,
    repoUrl,
    strategyAssistantContext,
    connectState,
    setRepoAnalysis,
    discoveryState,
    currentToken,
    isLocalRepoRef,
    extractLocalRepoPath,
    sourceVersionStatus,
    applyDetectedSourceVersion,
    setUserSelectedVersion,
    documentGenerationLoading,
    conversionDecision,
    setConversionDecision,
    showFolderStructure,
    setShowFolderStructure,
    handleCheckMicroserviceEligibility,
    handleGenerateBrdDocument,
    handleOpenFrameworkFile,
    isDiscoveryPending,
    formattedAnalysisElapsed,
    formattedAnalysisCompleted,
    detectedJavaStructureLabel,
    technicalSpecificationButtonLabel,
    technicalSpecificationHelperText,
    strategyState,
    repoAnalysis,
    riskLevel,
    buildToolDisplayLabel,
    renderCategorizedDependencies,
    sourceAlreadyAtLatestSupportedVersion,
    effectiveTargetVersion,
    handleTargetVersionChange,
    targetVersions,
    versionRecommendationLoading,
    versionRecommendationError,
    versionRecommendation,
    versionRecommendationCards,
    migrationApproachOptions,
    targetRepoName,
    handleTargetRepoNameChange,
    getAutoGeneratedTargetName,
    targetRepositoryHost,
    targetRepositoryOwner,
    continueWithTargetVersion,
    modernizationState,
    functionalTestToolMethod,
    setFunctionalTestToolMethod,
    functionalTestingTools,
    hasUI,
    localApiTestCases,
    loading,
    handleStartMigration,
    migrationJob,
    migrationTimerNow,
    animationProgress,
    runFossa,
    runSonar,
    runTests,
    selectedSourceVersion,
    resetWizard,
    resultExecState,
    selectedLLMProvider,
    useLLMTests,
    renderStepIndicator,
  } = useWizardController();

  return (
    <div style={styles.container}>
      {step === 3 && <StrategyChatWidget repoUrl={selectedRepo?.url} strategyContext={strategyAssistantContext} />}
      <div style={styles.stepIndicatorContainer}>{renderStepIndicator()}</div>
      <div style={styles.main}>
        {error && <div style={styles.errorBanner}><span>{error}</span><button style={styles.errorClose} onClick={() => setError("")}><FaTimes /></button></div>}
        {step === 1 && (
          <ConnectPage>
            <ConnectStepView
              connect={connectState}
              onError={setError}
              onClearRepoAnalysis={() => setRepoAnalysis(null)}
            />
          </ConnectPage>
        )}
        {step === 2 && (
          <DiscoveryPage>
            <DiscoveryStepView
              discovery={discoveryState}
              selectedRepo={selectedRepo}
              currentToken={currentToken}
              repoUtils={{ isLocalRepoRef, extractLocalRepoPath }}
              sourceVersionStatus={sourceVersionStatus}
              applyDetectedSourceVersion={applyDetectedSourceVersion}
              setUserSelectedVersion={setUserSelectedVersion}
              documentGenerationLoading={documentGenerationLoading}
              conversionDecision={conversionDecision}
              setConversionDecision={setConversionDecision}
              showFolderStructure={showFolderStructure}
              setShowFolderStructure={setShowFolderStructure}
              handleCheckMicroserviceEligibility={handleCheckMicroserviceEligibility}
              handleGenerateBrdDocument={handleGenerateBrdDocument}
              handleOpenFrameworkFile={handleOpenFrameworkFile}
              isDiscoveryPending={isDiscoveryPending}
              formattedAnalysisElapsed={formattedAnalysisElapsed}
              formattedAnalysisCompleted={formattedAnalysisCompleted}
              detectedJavaStructureLabel={detectedJavaStructureLabel}
              technicalSpecificationButtonLabel={technicalSpecificationButtonLabel}
              technicalSpecificationHelperText={technicalSpecificationHelperText}
              onBack={() => setStep(1)}
              onChooseDifferentRepository={() => {
                setStep(1);
                setSelectedRepo(null);
                setRepoAnalysis(null);
                setRepoUrl("");
              }}
              onContinueToStrategy={() => setStep(3)}
              onError={setError}
            />
          </DiscoveryPage>
        )}
        {step === 3 && (
          <StrategyPage>
            <StrategyStepView
              strategy={strategyState}
              repoAnalysis={repoAnalysis}
              selectedRepo={selectedRepo}
              riskLevel={riskLevel}
              stepSummary="Review assessment results and define the migration roadmap"
              buildToolDisplayLabel={buildToolDisplayLabel}
              renderCategorizedDependencies={renderCategorizedDependencies}
              sourceAlreadyAtLatestSupportedVersion={sourceAlreadyAtLatestSupportedVersion}
              effectiveTargetVersion={effectiveTargetVersion}
              handleTargetVersionChange={handleTargetVersionChange}
              availableTargetVersions={targetVersions}
              versionRecommendationLoading={versionRecommendationLoading}
              versionRecommendationError={versionRecommendationError}
              versionRecommendation={versionRecommendation}
              versionRecommendationCards={versionRecommendationCards}
              migrationApproachOptions={migrationApproachOptions}
              targetRepoName={targetRepoName}
              handleTargetRepoNameChange={handleTargetRepoNameChange}
              getAutoGeneratedTargetName={getAutoGeneratedTargetName}
              targetRepositoryHost={targetRepositoryHost}
              targetRepositoryOwner={targetRepositoryOwner}
              onBack={() => setStep(2)}
              onContinue={() => continueWithTargetVersion(4)}
            />
          </StrategyPage>
        )}
        {step === 4 && (
          <ModernizationPage>
            <ModernizationStepView
              modernization={modernizationState}
              repoAnalysis={repoAnalysis}
              selectedRepo={selectedRepo}
              repoUrl={repoUrl}
              currentToken={currentToken}
              functionalTestToolMethod={functionalTestToolMethod}
              setFunctionalTestToolMethod={setFunctionalTestToolMethod}
              functionalTestingTools={functionalTestingTools}
              hasUI={hasUI}
              localApiTestCases={localApiTestCases}
              loading={loading}
              repoUtils={{ isLocalRepoRef, extractLocalRepoPath }}
              onBack={() => setStep(3)}
              onStartMigration={handleStartMigration}
            />
          </ModernizationPage>
        )}
        {step === 5 && (
          <ResultPage>
            <MigrationAnimationView
              loading={loading}
              migrationJob={migrationJob}
              migrationTimerNow={migrationTimerNow}
              animationProgress={animationProgress}
              runFossa={runFossa}
              runSonar={runSonar}
              runTests={runTests}
              selectedRepoName={selectedRepo?.name}
              repoUrl={repoUrl}
              selectedSourceVersion={selectedSourceVersion}
              effectiveTargetVersion={effectiveTargetVersion}
            />
          </ResultPage>
        )}
        {step === 6 && (
          <ResultPage>
            <MigrationProgressView
              migrationJob={migrationJob}
              migrationTimerNow={migrationTimerNow}
              onCancel={() => {
                setError("");
                resetWizard();
              }}
              onViewReport={() => setStep(7)}
            />
          </ResultPage>
        )}
        {step === 7 && (
          <ResultPage>
            <ResultReportView
              resultExec={resultExecState}
              runSonar={runSonar}
              runFossa={runFossa}
              selectedLLMProvider={selectedLLMProvider}
              useLLMTests={useLLMTests}
              resetWizard={resetWizard}
              onBack={() => setStep(4)}
              onError={(message) => setError(message)}
            />
          </ResultPage>
        )}
      </div>
    </div>
  );
}
