import { FaCode, FaCogs, FaJava, FaLeaf, FaProjectDiagram } from "react-icons/fa";
import { wizardStyles as styles } from "@/shared/components/wizard/wizardStyles";
import {
  renderWizardIconBadge,
  renderBackButtonLabel,
  renderForwardButtonLabel,
  WizardInfoTooltip,
  WizardOptionCard,
  WizardSectionHeading,
} from "@/shared/components/wizard";
import type { RepoAnalysis, RepoInfo, DependencyInfo } from "@/shared/types/domain";
import type { JavaVersionRecommendationResponse } from "../services/strategyService";
import type { useStrategyState, JavaVersionOption } from "../hooks/useStrategyState";

const getJavaVersionRecommendationProviderLabel = (providerUsed?: string | null) => {
  const normalized = String(providerUsed || "").trim().toLowerCase();
  if (normalized === "huggingface") return "AI Recommendations (Hugging Face)";
  if (normalized === "openai") return "ChatGPT Recommendations";
  if (normalized === "heuristic") return "Smart Recommendations";
  return "Java Upgrade Recommendations";
};

const getJavaVersionRecommendationLoadingLabel = (providerUsed?: string | null) => {
  const normalized = String(providerUsed || "").trim().toLowerCase();
  if (normalized === "huggingface") return "Fetching recommended target Java version from Hugging Face...";
  if (normalized === "openai") return "Fetching recommended target Java version from ChatGPT...";
  return "Fetching recommended target Java version...";
};

interface MigrationApproachOption {
  value: "fork" | "branch" | "local";
  label: string;
  desc: string;
  tooltip: string;
  icon: React.ReactNode;
  color: string;
}

interface VersionRecommendationCard {
  version: string;
  eyebrow: string;
  label: string;
  description: string;
  helper: string;
  badgeBackground: string;
  badgeColor: string;
}

interface StrategyStepViewProps {
  strategy: ReturnType<typeof useStrategyState>;
  repoAnalysis: RepoAnalysis | null;
  selectedRepo: RepoInfo | null;
  riskLevel: string;
  stepSummary: string;
  buildToolDisplayLabel: string;
  renderCategorizedDependencies: (dependencies: DependencyInfo[]) => React.ReactNode;
  effectiveTargetVersion: string;
  handleTargetVersionChange: (value: string) => void;
  availableTargetVersions: JavaVersionOption[];
  versionRecommendationLoading: boolean;
  versionRecommendationError: string | null;
  versionRecommendation: JavaVersionRecommendationResponse | null;
  versionRecommendationCards: VersionRecommendationCard[];
  migrationApproachOptions: MigrationApproachOption[];
  targetRepoName: string;
  handleTargetRepoNameChange: (value: string) => void;
  getAutoGeneratedTargetName: (approach: "fork" | "branch" | "local") => string;
  targetRepositoryHost: string;
  targetRepositoryOwner: string;
  onBack: () => void;
  onContinue: () => void;
}

export function StrategyStepView({
  strategy,
  repoAnalysis,
  selectedRepo,
  riskLevel,
  stepSummary,
  buildToolDisplayLabel,
  renderCategorizedDependencies,
  effectiveTargetVersion,
  handleTargetVersionChange,
  availableTargetVersions,
  versionRecommendationLoading,
  versionRecommendationError,
  versionRecommendation,
  versionRecommendationCards,
  migrationApproachOptions,
  targetRepoName,
  handleTargetRepoNameChange,
  getAutoGeneratedTargetName,
  targetRepositoryHost,
  targetRepositoryOwner,
  onBack,
  onContinue,
}: StrategyStepViewProps) {
  const {
    selectedSourceVersion,
    setSelectedSourceVersion,
    selectedTargetVersion,
    selectedConversions,
    setSelectedConversions,
    targetVersionRequiredError,
    targetRepoNameError,
    setTargetRepoNameError,
    migrationApproach,
    setMigrationApproach,
    userSelectedVersion,
    setUserSelectedVersion,
  } = strategy;
  const detectedSourceVersion =
    (repoAnalysis?.java_version || repoAnalysis?.java_version_from_build || selectedSourceVersion).toString().trim();

  // Spring -> Spring Boot conversion card: enabled/disabled purely from the
  // backend's Discovery-stage analysis of the actual cloned repository (never
  // guessed from the repo name/URL). Until that analysis result is present on
  // repoAnalysis, the card stays in a disabled "analyzing" state.
  const springEligibility = repoAnalysis?.spring_boot_eligibility;
  const springBootPathwayStatus: "loading" | "conversion" | "upgrade" | "disabled" = !repoAnalysis
    ? "loading"
    : !springEligibility || !springEligibility.repositoryAnalyzed
      ? "loading"
      : springEligibility.springBootConversionEligible
        ? "conversion"
        : springEligibility.springBootUpgradeEligible
          ? "upgrade"
          : "disabled";
  const springBootReason =
    springEligibility?.eligibilityReason ??
    (repoAnalysis ? "Analyzing repository for Spring Boot eligibility..." : "Connect a repository to check Spring Boot eligibility.");
  const springBootTitle =
    springBootPathwayStatus === "upgrade" ? "Spring Boot Version Upgrade" : "Spring -> Spring Boot";
  const springBootDesc =
    springBootPathwayStatus === "upgrade"
      ? "Upgrade the existing Spring Boot version toward your target Java version."
      : "Convert a traditional Spring Framework project to Spring Boot.";
  const springBootBadgeLabel =
    springBootPathwayStatus === "loading"
      ? "Analyzing..."
      : springBootPathwayStatus === "disabled"
        ? "Not Eligible"
        : springBootPathwayStatus === "upgrade"
          ? "Upgrade Available"
          : "Active";

  return (
    <div style={styles.card}>
      <div style={styles.stepHeader}>
        {renderWizardIconBadge(<FaProjectDiagram />, "#f97316", "xl")}
        <div>
          <h2 style={styles.title}>Assessment &amp; Migration Strategy</h2>
          <p style={styles.subtitle}>{stepSummary}</p>
        </div>
      </div>

      {selectedRepo && repoAnalysis && (
        <>
          <WizardSectionHeading
            title="Application Assessment"
            style={{ marginBottom: 14, marginTop: 20 }}
          />

          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 18 }}>
            <div
              style={{
                ...styles.riskBadge,
                backgroundColor:
                  riskLevel === "low"
                    ? "#dcfce7"
                    : riskLevel === "medium"
                      ? "#fef3c7"
                      : "#fee2e2",
                color:
                  riskLevel === "low"
                    ? "#166534"
                    : riskLevel === "medium"
                      ? "#92400e"
                      : "#991b1b",
                marginBottom: 0,
              }}
            >
              Risk Level: {riskLevel.toUpperCase()}
            </div>

            <WizardInfoTooltip
              label="Risk level explanation"
              width={300}
              placement="left"
              panelStyle={{ borderRadius: 10, padding: "16px 20px", boxShadow: "0 18px 35px rgba(15, 23, 42, 0.25)" }}
            >
              <div style={{ color: "#86efac", fontWeight: 800, fontSize: 14, marginBottom: 12 }}>
                ANALYSIS
              </div>
              <div style={{ fontSize: 16, fontWeight: 700, lineHeight: 1.45 }}>
                {riskLevel === "low"
                  ? "The project is already on a modern migration path with build tooling and tests detected."
                  : riskLevel === "medium"
                    ? "The project has build tooling, but tests are missing or limited."
                    : "The project needs extra review because build tooling or Java metadata was not detected."}
              </div>
            </WizardInfoTooltip>
          </div>

          <div style={styles.assessmentGrid}>
            <div style={styles.assessmentItem}><div style={styles.assessmentLabel}>Build Tool</div><div style={styles.assessmentValue}>{buildToolDisplayLabel}</div></div>
            <div style={styles.assessmentItem}><div style={styles.assessmentLabel}>Java Version</div><div style={styles.assessmentValue}>{repoAnalysis.java_version || "Unknown"}</div></div>
            <div style={styles.assessmentItem}><div style={styles.assessmentLabel}>Has Tests</div><div style={styles.assessmentValue}>{repoAnalysis.has_tests ? "Yes" : "No"}</div></div>
            <div style={styles.assessmentItem}><div style={styles.assessmentLabel}>Dependencies</div><div style={styles.assessmentValue}>{repoAnalysis.dependencies?.length || 0} found</div></div>
          </div>

          {repoAnalysis.dependencies && repoAnalysis.dependencies.length > 0 && (
            <div style={styles.field}>
              {renderCategorizedDependencies(repoAnalysis.dependencies)}
            </div>
          )}

          <div
            style={{
              background: "#fff",
              border: "1px solid #dbe3ef",
              borderRadius: 14,
              padding: "26px 30px",
              boxShadow: "0 2px 8px rgba(15, 23, 42, 0.06)",
              marginBottom: 26,
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                fontSize: 20,
                fontWeight: 800,
                color: "#0f172a",
                marginBottom: 18,
              }}
            >
              <span>Setup</span>
              <span>Conversion Type</span>
            </div>

            <div style={{ height: 1, background: "#dbe3ef", marginBottom: 18 }} />

            <p style={{ fontSize: 17, color: "#475569", margin: "0 0 22px" }}>
              Available modernization pathways for your project:
            </p>

            <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 14 }}>
              {[
                {
                  key: "java_version",
                  title: "Java Version Upgrade",
                  desc: "Upgrade Java version with Dependencies update",
                  icon: <FaJava />,
                  color: "#2563eb",
                  disabled: false,
                  badgeLabel: "Active",
                  detail: null as React.ReactNode,
                },
                {
                  key: "build_conversion",
                  title: "Maven -> Gradle | Gradle -> Maven",
                  desc: "Convert pom.xml to build.gradle with dependency mapping",
                  icon: <FaCogs />,
                  color: "#8b5cf6",
                  disabled: true,
                  badgeLabel: "Coming Soon",
                  detail: null as React.ReactNode,
                },
                {
                  key: "microservices",
                  title: "Monolithic -> Microservices",
                  desc: "Decompose monolith into microservices architecture",
                  icon: <FaProjectDiagram />,
                  color: "#0ea5e9",
                  disabled: true,
                  badgeLabel: "Coming Soon",
                  detail: null as React.ReactNode,
                },
                {
                  key: "jakarta",
                  title: "javax -> Jakarta EE | Jakarta EE -> javax",
                  desc: "Migrate javax.* packages to jakarta.*",
                  icon: <FaCode />,
                  color: "#f59e0b",
                  disabled: true,
                  badgeLabel: "Coming Soon",
                  detail: null as React.ReactNode,
                },
                {
                  key: "spring_boot",
                  title: springBootTitle,
                  desc: springBootDesc,
                  icon: <FaLeaf />,
                  color: springBootPathwayStatus === "disabled" || springBootPathwayStatus === "loading" ? "#94a3b8" : "#22c55e",
                  disabled: springBootPathwayStatus === "disabled" || springBootPathwayStatus === "loading",
                  badgeLabel: springBootBadgeLabel,
                  detail: (
                    <span
                      style={{
                        fontWeight: 600,
                        color:
                          springBootPathwayStatus === "conversion" || springBootPathwayStatus === "upgrade"
                            ? "#166534"
                            : "#64748b",
                      }}
                    >
                      {springBootReason}
                    </span>
                  ) as React.ReactNode,
                },
                {
                  key: "ui_modernization",
                  title: "JSP/JSF -> Angular/React",
                  desc: "Modernize legacy JSP/JSF views to Angular or React SPA",
                  icon: <FaCode />,
                  color: "#06b6d4",
                  disabled: true,
                  badgeLabel: "Coming Soon",
                  detail: null as React.ReactNode,
                },
              ].map((pathway) => {
                const isActivePathway = selectedConversions.includes(pathway.key);
                const isDisabledPathway = pathway.disabled;

                return (
                  <WizardOptionCard
                    key={pathway.key}
                    onClick={() => {
                      if (isDisabledPathway) return;
                      if (pathway.key === "java_version") {
                        setSelectedConversions(["java_version"]);
                        return;
                      }
                      setSelectedConversions((prev) => {
                        const base = prev.includes("java_version") ? ["java_version"] : [];
                        return prev.includes(pathway.key) ? base : [...base, pathway.key];
                      });
                    }}
                    accent={pathway.color}
                    selected={isActivePathway}
                    disabled={isDisabledPathway}
                    iconBadge={renderWizardIconBadge(pathway.icon, pathway.color, "sm")}
                    title={pathway.title}
                    description={pathway.desc}
                    detail={pathway.detail}
                    topRight={
                      <div className={`wizard-pathway-status${isDisabledPathway ? " is-disabled" : ""}`}>
                        {pathway.badgeLabel}
                      </div>
                    }
                    containerStyle={{
                      minHeight: 96,
                      justifyContent: "center",
                    }}
                    titleStyle={{ color: isActivePathway ? pathway.color : "#1e293b" }}
                    descriptionStyle={{ color: isDisabledPathway ? "#475569" : "#334155" }}
                  />
                );
              })}
            </div>
          </div>
        </>
      )}

      <div style={styles.row}>
        <div style={styles.field}>
          <label style={styles.label}>Source Java Version</label>
          <div style={{
            padding: "12px 14px",
            fontSize: 14,
            borderRadius: 8,
            border: "1px solid #d1d5db",
            backgroundColor: "#f9fafb",
            color: userSelectedVersion ? "#1e293b" : "#6b7280",
            fontWeight: userSelectedVersion ? 600 : 500
          }}>
            {userSelectedVersion
              ? `Java ${selectedSourceVersion} (manually selected)`
              : (repoAnalysis?.java_version && repoAnalysis?.java_version !== "unknown"
                  ? `Java ${repoAnalysis.java_version} (detected)`
                  : "Source don't have a java version")
            }
          </div>
          <p style={styles.helpText}>
            {userSelectedVersion
              ? "Source version manually selected in discovery step"
              : (repoAnalysis?.java_version && repoAnalysis?.java_version !== "unknown"
                  ? "Java version detected from build configuration"
                  : "No Java version found - please select a source version below")
            }
          </p>
          {!userSelectedVersion && (!((repoAnalysis?.java_version || repoAnalysis?.java_version_from_build)) || (repoAnalysis?.java_version || repoAnalysis?.java_version_from_build) === "unknown") && (
            <div style={{ marginTop: 12 }}>
              <select
                value={selectedSourceVersion}
                onChange={(e) => {
                  setSelectedSourceVersion(e.target.value);
                  setUserSelectedVersion(e.target.value);
                }}
                style={{
                  padding: "10px 14px",
                  borderRadius: 6,
                  border: "1px solid #d97706",
                  fontSize: 14,
                  backgroundColor: "#fff",
                  cursor: "pointer",
                  width: "100%"
                }}
              >
                <option value="7">Java 7 (Legacy)</option>
                <option value="8">Java 8 (LTS)</option>
                <option value="11">Java 11 (LTS)</option>
                <option value="17">Java 17 (LTS)</option>
                <option value="21">Java 21 (LTS)</option>
                <option value="22">Java 22</option>
                <option value="23">Java 23</option>
                <option value="24">Java 24</option>
                <option value="25">Java 25 (LTS)</option>
              </select>
              <div style={{ fontSize: 11, color: "#a16207", marginTop: 6 }}>
                Select the correct Java version for your project. This will be used as the source version for migration.
              </div>
            </div>
          )}
        </div>
        <div style={styles.field}>
          <label style={{ ...styles.label, ...(targetVersionRequiredError ? styles.labelError : {}) }}>
            Target Java Version <span style={styles.requiredMark}>*</span>
          </label>
          <select
            style={{ ...styles.select, ...(targetVersionRequiredError ? styles.selectError : {}) }}
            value={effectiveTargetVersion}
            onChange={(e) => handleTargetVersionChange(e.target.value)}
            disabled={availableTargetVersions.length === 0}
          >
            <option value="" disabled>Select Java Version</option>
            {availableTargetVersions.map((v) => <option key={v.value} value={v.value}>{v.label}</option>)}
          </select>
          {targetVersionRequiredError && (
            <p style={styles.fieldErrorText}>Target Java Version is required.</p>
          )}
          <p style={styles.helpText}>
            {availableTargetVersions.length === 0
              ? `No supported target Java version is newer than detected Java ${detectedSourceVersion}.`
              : "Only versions newer than the detected source Java version are available"}
          </p>
        </div>
      </div>

      {availableTargetVersions.length > 0 && versionRecommendationLoading && (
        <div style={{ ...styles.infoBox, marginBottom: 20 }}>
          {getJavaVersionRecommendationLoadingLabel("huggingface")}
        </div>
      )}
      {availableTargetVersions.length > 0 && !versionRecommendationLoading && versionRecommendationError && (
        <div style={{ ...styles.errorBox, marginBottom: 20 }}>
          {versionRecommendationError}
        </div>
      )}
      {availableTargetVersions.length > 0 && !versionRecommendationLoading && !versionRecommendationError && versionRecommendation && (
        <div style={{ marginBottom: 20 }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: "#1d4ed8", textTransform: "uppercase", letterSpacing: "0.4px", marginBottom: 10 }}>
            {getJavaVersionRecommendationProviderLabel(versionRecommendation.provider_used)}
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12 }}>
            {versionRecommendationCards.map((card) => {
              const isSelected = selectedTargetVersion === card.version;
              return (
                <button
                  key={card.version}
                  type="button"
                  onClick={() => handleTargetVersionChange(card.version)}
                  style={{
                    textAlign: "left",
                    padding: 12,
                    borderRadius: 10,
                    border: `2px solid ${isSelected ? "#22c55e" : "#e2e8f0"}`,
                    background: isSelected
                      ? "linear-gradient(135deg, #ecfdf5 0%, #f0fdf4 100%)"
                      : "#fff",
                    boxShadow: isSelected
                      ? "0 8px 24px rgba(34, 197, 94, 0.18)"
                      : "0 2px 8px rgba(15, 23, 42, 0.06)",
                    cursor: "pointer",
                    transition: "all 0.2s ease",
                  }}
                >
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, marginBottom: 8 }}>
                    <span
                      style={{
                        display: "inline-flex",
                        alignItems: "center",
                        padding: "2px 7px",
                        borderRadius: 999,
                        backgroundColor: isSelected ? "#22c55e" : card.badgeBackground,
                        color: isSelected ? "#fff" : card.badgeColor,
                        fontSize: 9,
                        fontWeight: 800,
                        textTransform: "uppercase",
                        letterSpacing: "0.4px",
                      }}
                    >
                      {isSelected ? "Selected" : card.eyebrow}
                    </span>
                  </div>
                  <div style={{ fontSize: 20, fontWeight: 800, color: "#1e293b", marginBottom: 3 }}>
                    Java {card.version}
                  </div>
                  <div style={{ fontSize: 10, color: "#64748b", fontWeight: 600, marginBottom: 7 }}>
                    {card.label}
                  </div>
                  <div style={{ fontSize: 11, color: "#334155", lineHeight: 1.4, minHeight: 48 }}>
                    {card.description}
                  </div>
                  <div style={{ fontSize: 9, color: isSelected ? "#16a34a" : "#94a3b8", marginTop: 8, fontWeight: 700 }}>
                    {isSelected ? `Selected for migration` : card.helper}
                  </div>
                </button>
              );
            })}
          </div>
          {((versionRecommendation.benefits?.length ?? 0) > 0 ||
            (versionRecommendation.compatibility_considerations?.length ?? 0) > 0) && (
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
                gap: 12,
                marginTop: 12,
              }}
            >
              {(versionRecommendation.benefits?.length ?? 0) > 0 && (
                <div
                  style={{
                    padding: 12,
                    borderRadius: 10,
                    border: "1px solid #bbf7d0",
                    background: "#f0fdf4",
                  }}
                >
                  <div style={{ fontSize: 11, fontWeight: 700, color: "#166534", textTransform: "uppercase", letterSpacing: "0.4px", marginBottom: 6 }}>
                    Upgrade Benefits
                  </div>
                  <ul style={{ margin: 0, paddingLeft: 16, fontSize: 12, color: "#15803d", lineHeight: 1.6 }}>
                    {versionRecommendation.benefits!.map((benefit, index) => (
                      <li key={index}>{benefit}</li>
                    ))}
                  </ul>
                </div>
              )}
              {(versionRecommendation.compatibility_considerations?.length ?? 0) > 0 && (
                <div
                  style={{
                    padding: 12,
                    borderRadius: 10,
                    border: "1px solid #fde68a",
                    background: "#fffbeb",
                  }}
                >
                  <div style={{ fontSize: 11, fontWeight: 700, color: "#92400e", textTransform: "uppercase", letterSpacing: "0.4px", marginBottom: 6 }}>
                    Compatibility Considerations
                  </div>
                  <ul style={{ margin: 0, paddingLeft: 16, fontSize: 12, color: "#a16207", lineHeight: 1.6 }}>
                    {versionRecommendation.compatibility_considerations!.map((item, index) => (
                      <li key={index}>{item}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}
        </div>
      )}

      <WizardSectionHeading
        title="Migration Destination"
        style={{ marginBottom: 14, marginTop: 20 }}
      />
      <div style={styles.field}>
        <label style={styles.label}>Destination repository setup</label>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 14 }}>
          {migrationApproachOptions.map((opt) => (
            <WizardOptionCard
              key={opt.value}
              accent={opt.color}
              selected={migrationApproach === opt.value}
              iconBadge={renderWizardIconBadge(opt.icon, opt.color, "md")}
              title={opt.label}
              description={opt.desc}
              onClick={() => {
                setMigrationApproach(opt.value);
                setTargetRepoNameError("");
              }}
              topRight={
                <div style={{ position: "absolute", top: 12, right: 12 }}>
                  <WizardInfoTooltip
                    label={`${opt.label} details`}
                    triggerClassName="ui-info-trigger ui-info-trigger-light"
                  >
                    <div style={{ fontWeight: 600, marginBottom: 8, color: "#94a3b8" }}>
                      {opt.label} Details
                    </div>
                    <div>{opt.tooltip}</div>
                  </WizardInfoTooltip>
                </div>
              }
              headerStyle={{ alignItems: "center" }}
              titleStyle={{ marginBottom: 4 }}
            />
          ))}
        </div>
      </div>

      <div style={styles.field}>
        <label style={{ ...styles.label, ...(targetRepoNameError ? styles.labelError : {}) }}>
          {migrationApproach === "branch"
            ? "Target Branch Name"
            : migrationApproach === "local"
              ? "Target Local Folder Path"
              : "Target Repository Name"}
        </label>
        <div style={{ display: "flex", gap: 8 }}>
          <input
            type="text"
            style={{
              ...styles.input,
              flex: 1,
              backgroundColor: migrationApproach === "fork" ? "#f8fafc" : "#f0fdf4",
              borderColor: targetRepoNameError ? "#ef4444" : "#22c55e",
              color: migrationApproach === "fork" ? "#64748b" : styles.input.color,
            }}
            value={targetRepoName}
            onChange={(e) => handleTargetRepoNameChange(e.target.value)}
            readOnly={migrationApproach === "fork"}
            placeholder={
              migrationApproach === "branch"
                ? getAutoGeneratedTargetName("branch")
                : migrationApproach === "local"
                  ? getAutoGeneratedTargetName("local")
                  : getAutoGeneratedTargetName("fork")
            }
          />
        </div>
        {targetRepoNameError && (
          <p style={styles.fieldErrorText}>{targetRepoNameError}</p>
        )}
        <p style={styles.helpText}>
          Format: <code style={{ backgroundColor: "#f1f5f9", padding: "2px 6px", borderRadius: 4, fontSize: 11 }}>
            {migrationApproach === "branch"
              ? <>migration/{'{source-repo}'}-Migrated{'{timestamp}'}</>
              : migrationApproach === "local"
                ? <>{'{source-repo}'}-Migrated or C:\Users\you\Desktop\{'{source-repo}'}-Migrated</>
                : <>https://{targetRepositoryHost}/{targetRepositoryOwner}/{'{source-repo}'}-Migrated{'{timestamp}'}</>}
          </code> {migrationApproach === "fork" ? "(auto-generated, read only)" : "(auto-generated, editable)"}
        </p>
        {migrationApproach === "fork" && (
          <p style={styles.helpText}>
            New repository targets are generated automatically for the configured GitHub owner.
          </p>
        )}
        {migrationApproach === "local" && (
          <p style={styles.helpText}>
            Enter either a folder name or a full absolute path. If only a folder name is provided, the backend migration workspace will be used.
          </p>
        )}
      </div>

      <div style={styles.btnRow}>
        <button style={styles.secondaryBtn} onClick={onBack}>{renderBackButtonLabel()}</button>
        <button style={styles.primaryBtn} onClick={onContinue}>{renderForwardButtonLabel("Continue to Migration")}</button>
      </div>
    </div>
  );
}
