import type { CSSProperties } from "react";

export const wizardStyles: { [key: string]: CSSProperties } = {
  container: { minHeight: "100vh", width: "100%", maxWidth: "100vw", margin: 0, padding: 0, background: "#f8fafc", fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", overflow: "hidden" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 40px", width: "100%", boxSizing: "border-box", background: "#fff", borderBottom: "1px solid #e2e8f0" },
  logo: { display: "flex", alignItems: "center", gap: 12 },
  stepIndicatorContainer: { background: "#fff", borderBottom: "1px solid #e2e8f0", padding: "24px 40px", width: "100%", boxSizing: "border-box", overflowX: "auto" },
  stepIndicator: { display: "flex", gap: 0, justifyContent: "center", alignItems: "flex-start", minWidth: "fit-content", flexWrap: "nowrap" },
  stepItem: { display: "flex", alignItems: "center", gap: 8, padding: "6px 12px", borderRadius: 8, transition: "all 0.2s ease", cursor: "pointer", whiteSpace: "nowrap" },
  stepCircle: { width: 44, height: 44, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, fontWeight: 600, transition: "all 0.2s ease" },
  stepLabel: { display: "flex", flexDirection: "column" },
  main: { width: "100%", maxWidth: "100vw", padding: "24px 40px", minHeight: "calc(100vh - 160px)", boxSizing: "border-box" },
  card: { background: "#fff", borderRadius: 12, padding: "28px 32px", boxShadow: "0 1px 3px rgba(0,0,0,0.1)", marginBottom: 20, width: "100%", boxSizing: "border-box", border: "1px solid #e2e8f0" },
  stepHeader: { display: "flex", alignItems: "flex-start", gap: 16, marginBottom: 24, paddingBottom: 20, borderBottom: "1px solid #e2e8f0", flexWrap: "wrap" },
  stepIcon: { fontSize: 36 },
  timerBadge: { marginLeft: "auto", display: "flex",flexDirection: "row",alignItems: "center" /*flexDirection: "column", alignItems: "flex-end"*/, gap: 10, padding: "10px 14px", borderRadius: 10, background: "#fff2e7", opacity:0.7, border: "1px solid #f5c6a5", /*minWidth: 110*/minWidth: 210,
  whiteSpace: "nowrap",flexWrap: "nowrap", },
   icon: {
    fontSize: "28px"
  },
  timerLabel: { fontSize: 18, display:"inline-flex", alignItems:"center", fontWeight: 700, color: "#000000", fontFamily: "Arial", letterSpacing: "0.5px" },
  timerValue: { fontSize: 18, fontWeight: 700, color: "#000000", fontVariantNumeric: "tabular-nums", whiteSpace:"nowrap" },
  migrationTimerSection: { marginBottom: 0 },
  migrationTimerCard: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    padding: 0,
    borderRadius: 0,
    background: "transparent",
    border: "none",
    boxShadow: "none",
  },
  migrationTimerHero: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    justifyContent: "flex-start",
    flexWrap: "nowrap",
  },
  migrationTimerOrb: {
    width: 64,
    height: 64,
    borderRadius: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  migrationTimerOrbInner: {
    width: 38,
    height: 38,
    borderRadius: 12,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 17,
    opacity: 0.9,
  },
  migrationTimerLabel: {
    fontSize: 11,
    fontWeight: 800,
    fontFamily: "'Manrope', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    textTransform: "uppercase",
    letterSpacing: "0.18em",
    marginBottom: 6,
    textAlign: "left",
  },
  migrationTimerCopy: {
    minWidth: 0,
    flex: "0 1 auto",
    textAlign: "left",
  },
  migrationTimerValue: {
    color: "#0f172a",
    fontFamily: "'Manrope', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    lineHeight: 0.92,
    fontVariantNumeric: "tabular-nums",
    fontFeatureSettings: '"tnum" 1, "lnum" 1',
    textAlign: "left",
  },
  migrationTimerSegment: {
    display: "inline-flex",
    alignItems: "baseline",
    gap: 2,
  },
  migrationTimerDigits: {
    fontSize: 40,
    fontWeight: 700,
    letterSpacing: "-0.05em",
  },
  migrationTimerUnit: {
    fontSize: 22,
    fontWeight: 600,
    letterSpacing: "-0.02em",
    color: "#334155",
    opacity: 0.72,
  },
  title: { fontSize: 22, fontWeight: 700, marginBottom: 6, color: "#1e293b" },
  subtitle: { fontSize: 14, color: "#64748b", margin: 0, lineHeight: 1.5 },
  discoveryStepTitle: {
    fontSize: 22,
    fontWeight: 700,
    marginBottom: 6,
    color: "#1e293b",
    lineHeight: 1.2,
    letterSpacing: 0,
    textTransform: "none",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  discoveryStepSubtitle: {
    fontSize: 14,
    color: "#64748b",
    margin: 0,
    lineHeight: 1.5,
    letterSpacing: 0,
    textTransform: "none",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  sectionTitle: { fontSize: 16, fontWeight: 600, color: "#1e293b", marginBottom: 14, marginTop: 20, display: "flex", alignItems: "center", gap: 8 },
  field: { marginBottom: 20, width: "100%", boxSizing: "border-box" },
  label: { fontWeight: 600, fontSize: 14, marginBottom: 8, display: "block", color: "#374151" },
  labelError: { color: "#b91c1c" },
  requiredMark: { color: "#dc2626", marginLeft: 4 },
  input: { width: "100%", padding: "12px 14px", fontSize: 14, borderRadius: 8, border: "1px solid #d1d5db", boxSizing: "border-box", transition: "all 0.2s ease", backgroundColor: "#fff" },
  select: { width: "100%", padding: "12px 14px", fontSize: 14, borderRadius: 8, border: "1px solid #d1d5db", backgroundColor: "#fff", transition: "all 0.2s ease", cursor: "pointer" },
  selectError: { border: "1px solid #f87171", boxShadow: "0 0 0 3px rgba(248, 113, 113, 0.15)", backgroundColor: "#fffafa" },
  fieldErrorText: { fontSize: 12, color: "#b91c1c", marginTop: 6, fontWeight: 600 },
  helpText: { fontSize: 13, color: "#64748b", marginTop: 6, lineHeight: 1.4 },
  infoButtonContainer: { position: "relative", display: "inline-block", zIndex: 100 },
  infoButton: { width: 22, height: 22, borderRadius: "50%", background: "#e5e7eb", border: "none", cursor: "pointer", fontSize: 12, color: "#6b7280", display: "inline-flex", alignItems: "center", justifyContent: "center", transition: "all 0.2s ease", padding: 0, fontWeight: 600 },
  tooltip: { display: "none", position: "absolute", bottom: "calc(100% + 10px)", left: 0, width: 280, background: "#1e293b", color: "#f1f5f9", padding: "14px", borderRadius: 8, fontSize: 13, zIndex: 1001, boxShadow: "0 10px 25px rgba(0,0,0,0.2)" },
  link: { color: "#2563eb", textDecoration: "none", fontWeight: 500 },
  infoBox: { background: "#eff6ff", border: "1px solid #bfdbfe", borderRadius: 8, padding: 16, marginBottom: 20, fontSize: 14, color: "#1e40af", width: "100%", boxSizing: "border-box", lineHeight: 1.5 },
  warningBox: { background: "#fffbeb", border: "1px solid #fcd34d", borderRadius: 8, padding: 16, marginBottom: 20, width: "100%", boxSizing: "border-box" },
  warningTitle: { fontWeight: 600, marginBottom: 10, color: "#78350f", fontSize: 14 },
  warningList: { margin: 0, paddingLeft: 18, fontSize: 14, color: "#92400e", lineHeight: 1.6 },
  errorBanner: { background: "#fef2f2", border: "1px solid #fca5a5", borderRadius: 8, padding: "12px 16px", marginBottom: 20, display: "flex", justifyContent: "space-between", alignItems: "center", color: "#991b1b", width: "100%", boxSizing: "border-box" },
  errorClose: { background: "none", border: "none", fontSize: 18, cursor: "pointer", color: "#dc2626" },
  errorBox: { background: "#fef2f2", border: "1px solid #fca5a5", borderRadius: 8, padding: "14px 16px", marginBottom: 20, color: "#991b1b", width: "100%", boxSizing: "border-box" },
  btnRow: { display: "flex", gap: 12, marginTop: 24, justifyContent: "flex-end", flexWrap: "wrap", alignItems: "center" },
  primaryBtn: {
    background: "linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)",
    color: "#fff",
    border: "1px solid #1d4ed8",
    borderRadius: 12,
    padding: "12px 20px",
    fontWeight: 700,
    cursor: "pointer",
    fontSize: 14,
    lineHeight: 1.2,
    minHeight: 46,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    boxShadow: "0 10px 24px rgba(37, 99, 235, 0.18)",
    transition: "all 0.2s ease",
  },
  secondaryBtn: {
    background: "#fff",
    color: "#1e293b",
    border: "1px solid #cbd5e1",
    borderRadius: 12,
    padding: "12px 20px",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: 14,
    lineHeight: 1.2,
    minHeight: 46,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    boxShadow: "0 6px 18px rgba(15, 23, 42, 0.06)",
    transition: "all 0.2s ease",
  },
  reportActionsBar: {
    display: "flex",
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    gap: 16,
    marginTop: 28,
    flexWrap: "wrap",
    alignItems: "center",
  },
  reportActionGroup: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
  },
  row: { display: "flex", gap: 20 },
  loadingBox: { display: "flex", alignItems: "center", justifyContent: "center", gap: 12, padding: 40, color: "#2563eb", fontWeight: 500, fontSize: 15 },
  spinner: { width: 24, height: 24, border: "3px solid #e5e7eb", borderTop: "3px solid #2563eb", borderRadius: "50%", animation: "spin 0.8s linear infinite" },
  repoList: { display: "flex", flexDirection: "column", gap: 8, maxHeight: 300, overflowY: "auto", paddingRight: 6 },
  repoItem: { display: "flex", alignItems: "center", gap: 12, padding: "14px 16px", border: "1px solid #e2e8f0", borderRadius: 8, cursor: "pointer", transition: "all 0.2s ease", backgroundColor: "#fff" },
  repoIcon: { fontSize: 20 },
  repoInfo: { flex: 1 },
  repoName: { fontWeight: 600, fontSize: 14, color: "#1e293b" },
  repoPath: { fontSize: 12, color: "#64748b", marginTop: 2 },
  repoLanguage: { fontSize: 11, padding: "4px 10px", background: "#eff6ff", borderRadius: 12, color: "#2563eb", fontWeight: 500 },
  arrow: { fontSize: 16, color: "#2563eb" },
  emptyText: { textAlign: "center", color: "#64748b", padding: 40, fontSize: 14 },
  selectedRepoBox: { display: "flex", alignItems: "center", gap: 12, padding: "12px 16px", background: "#eff6ff", borderRadius: 8, marginBottom: 20, border: "1px solid #bfdbfe" },
  changeBtn: { marginLeft: "auto", background: "none", border: "none", color: "#2563eb", cursor: "pointer", fontSize: 13, fontWeight: 600 },
  riskBadge: { display: "inline-block", padding: "8px 16px", borderRadius: 16, fontSize: 13, fontWeight: 600, marginBottom: 14 },
  assessmentGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 16, marginBottom: 20 },
  assessmentItem: { background: "#fff", padding: 18, borderRadius: 10, textAlign: "center", border: "1px solid #e2e8f0" },
  assessmentLabel: { fontSize: 11, color: "#64748b", marginBottom: 8, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.5px" },
  assessmentValue: { fontSize: 20, fontWeight: 700, color: "#1e293b" },
  structureBox: { background: "#f8fafc", padding: 18, borderRadius: 10, marginBottom: 20, border: "1px solid #e2e8f0" },
  structureTitle: { fontSize: 14, fontWeight: 600, marginBottom: 12, color: "#1e293b" },
  structureGrid: { display: "flex", gap: 14, flexWrap: "wrap" },
  structureFound: { color: "#059669", fontWeight: 600 },
  structureMissing: { color: "#9ca3af", fontWeight: 500 },
  dependenciesBox: { marginBottom: 20 },
  dependenciesList: {
    background: "#f8fffb",
    borderRadius: 16,
    padding: 16,
    border: "1px solid #d8f3e4",
    maxHeight: 320,
    overflowY: "auto",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.8)",
  },
  dependenciesGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12 },
  dependencyCard: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minHeight: 92,
    padding: 14,
    borderRadius: 12,
    border: "1px solid #dcefe3",
    background: "linear-gradient(180deg, #eefbf2 0%, #e9f8ee 100%)",
    boxShadow: "0 6px 16px rgba(15, 23, 42, 0.04)",
  },
  dependencyCardName: {
    color: "#334155",
    fontSize: 13,
    fontWeight: 600,
    lineHeight: 1.35,
    wordBreak: "break-word",
  },
  dependencyVersionCard: {
    color: "#64748b",
    fontSize: 12,
    fontFamily: "'JetBrains Mono', monospace",
  },
  dependencyStatusBadge: {
    alignSelf: "flex-start",
    fontSize: 10,
    letterSpacing: 0.6,
    padding: "4px 8px",
    borderRadius: 999,
    fontWeight: 700,
  },
  dependencyItem: { display: "flex", justifyContent: "space-between", padding: "10px 0", borderBottom: "1px solid #f1f5f9", fontSize: 13 },
  dependencyVersion: { color: "#2563eb", fontFamily: "'JetBrains Mono', monospace", fontWeight: 500 },
  moreItems: { textAlign: "center", color: "#2563eb", fontSize: 12, paddingTop: 10, fontWeight: 500 },
  dependencyInsightsPanel: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    padding: 18,
    boxShadow: "0 6px 20px rgba(15, 23, 42, 0.04)",
  },
  dependencyInsightsHeader: {
    marginBottom: 16,
  },
  dependencyInsightsTitle: {
    fontSize: 17,
    fontWeight: 700,
    color: "#1e293b",
    marginBottom: 6,
  },
  dependencyInsightsSubtitle: {
    fontSize: 13,
    color: "#64748b",
    lineHeight: 1.5,
  },
  dependencySummaryGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 12,
    marginBottom: 16,
  },
  dependencySummaryCard: {
    background: "#fff",
    border: "1px solid #e2e8f0",
    borderRadius: 14,
    padding: 14,
    textAlign: "center",
    boxShadow: "0 6px 16px rgba(15, 23, 42, 0.04)",
    transition: "all 0.2s ease",
  },
  dependencySummaryLabel: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    marginBottom: 8,
  },
  dependencySummaryValue: {
    fontSize: 24,
    fontWeight: 800,
    color: "#1e293b",
  },
  dependencyFilterBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginBottom: 16,
  },
  dependencyFilterLabel: {
    fontSize: 13,
    color: "#475569",
    fontWeight: 600,
  },
  dependencyFilterClearButton: {
    border: "1px solid #cbd5e1",
    background: "#fff",
    color: "#334155",
    borderRadius: 999,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  dependencyAlertBox: {
    background: "#fff7ed",
    border: "1px solid #fdba74",
    borderRadius: 14,
    padding: 16,
    marginBottom: 18,
  },
  dependencyAlertTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "#c2410c",
    marginBottom: 6,
  },
  dependencyAlertText: {
    fontSize: 13,
    color: "#9a3412",
    lineHeight: 1.55,
  },
  categorizedDependenciesSection: {
    marginTop: 18,
  },
  categorizedDependenciesSectionTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "#92400e",
    marginBottom: 12,
  },
  categorizedDependenciesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 12,
    maxHeight: 420,
    overflowY: "auto",
    paddingRight: 4,
  },
  dependencyEmptyState: {
    border: "1px dashed #cbd5e1",
    borderRadius: 14,
    padding: 20,
    textAlign: "center",
    color: "#64748b",
    background: "#f8fafc",
  },
  categorizedDependencyCard: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    minHeight: 150,
    padding: 14,
    borderRadius: 14,
    border: "1px solid #e2e8f0",
    boxShadow: "0 4px 12px rgba(15, 23, 42, 0.04)",
  },
  categorizedDependencyHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
  },
  categorizedDependencyName: {
    color: "#1e293b",
    fontSize: 13,
    fontWeight: 700,
    lineHeight: 1.4,
    wordBreak: "break-word",
  },
  categorizedDependencyVersion: {
    color: "#64748b",
    fontSize: 12,
    fontFamily: "'JetBrains Mono', monospace",
  },
  dependencyRiskBadge: {
    flexShrink: 0,
    fontSize: 10,
    letterSpacing: 0.6,
    padding: "4px 8px",
    borderRadius: 999,
    fontWeight: 800,
  },
  dependencyMetaRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    alignItems: "center",
  },
  dependencyCategoryBadge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 8px",
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.72)",
    color: "#334155",
    fontSize: 11,
    fontWeight: 700,
  },
  dependencyStatusPill: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 8px",
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.52)",
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.04em",
  },
  dependencyReasonText: {
    fontSize: 12,
    lineHeight: 1.5,
  },
  microservicePanel: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  microserviceSectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    flexWrap: "wrap",
  },
  microserviceSectionHeaderContent: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  microserviceSectionSummary: {
    fontSize: 13,
    color: "#64748b",
    lineHeight: 1.5,
  },
  microserviceSectionToggle: {
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    color: "#334155",
    borderRadius: 999,
    padding: "8px 14px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  microserviceHero: {
    border: "1px solid #e2e8f0",
    borderRadius: 20,
    padding: 20,
    boxShadow: "0 12px 28px rgba(15, 23, 42, 0.06)",
  },
  microserviceHeroHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    flexWrap: "wrap",
    marginBottom: 18,
  },
  microserviceHeroStatusRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    flex: 1,
    minWidth: 280,
  },
  microserviceHeroIcon: {
    width: 56,
    height: 56,
    borderRadius: 18,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: "0.12em",
    flexShrink: 0,
  },
  microserviceHeroStatusCopy: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    flex: 1,
  },
  microserviceHeroStatusLabel: {
    fontSize: 24,
    fontWeight: 800,
    lineHeight: 1.1,
  },
  microserviceHeroSummary: {
    fontSize: 14,
    color: "#334155",
    lineHeight: 1.7,
    maxWidth: 920,
  },
  microserviceHeroFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    gap: 16,
    flexWrap: "wrap",
  },
  microserviceHeroProgressBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    flex: 1,
    minWidth: 260,
  },
  microserviceHeroProgressMeta: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    fontSize: 13,
    color: "#334155",
  },
  microserviceHeroProgressTrack: {
    width: "100%",
    height: 9,
    borderRadius: 999,
    background: "rgba(226, 232, 240, 0.95)",
    overflow: "hidden",
  },
  microserviceHeroProgressFill: {
    height: "100%",
    borderRadius: 999,
    transition: "width 0.35s ease",
  },
  microserviceHeroMetaRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "flex-end",
  },
  microserviceHeroMetaPill: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: 999,
    padding: "8px 12px",
    background: "rgba(255,255,255,0.88)",
    border: "1px solid rgba(148, 163, 184, 0.28)",
    color: "#334155",
    fontSize: 12,
    fontWeight: 700,
  },
  microserviceHeroNote: {
    marginTop: 14,
    padding: "10px 12px",
    borderRadius: 12,
    background: "rgba(255,255,255,0.72)",
    border: "1px solid rgba(251, 191, 36, 0.35)",
    color: "#92400e",
    fontSize: 12,
    lineHeight: 1.5,
  },
  microserviceHeroDecisionShell: {
    marginTop: 16,
    paddingTop: 16,
    borderTop: "1px solid rgba(148, 163, 184, 0.22)",
    display: "grid",
    gap: 12,
  },
  microserviceHeroDecisionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  microserviceHeroDecisionTitle: {
    fontSize: 14,
    fontWeight: 800,
    color: "#991b1b",
  },
  microserviceHeroDecisionToggle: {
    border: "1px solid rgba(248, 113, 113, 0.35)",
    background: "#ffffff",
    color: "#b91c1c",
    borderRadius: 999,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  microserviceMetricGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 12,
  },
  microserviceMetricCard: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    padding: 16,
    boxShadow: "0 8px 18px rgba(15, 23, 42, 0.04)",
  },
  microserviceMetricValue: {
    fontSize: 24,
    fontWeight: 800,
    color: "#0f172a",
    marginBottom: 6,
  },
  microserviceMetricLabel: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: 700,
    lineHeight: 1.5,
  },
  microservicePreviewGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 12,
  },
  microservicePreviewCard: {
    border: "1px solid #e2e8f0",
    borderRadius: 18,
    padding: 16,
    boxShadow: "0 8px 22px rgba(15, 23, 42, 0.04)",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  microservicePreviewTitle: {
    fontSize: 13,
    fontWeight: 800,
    letterSpacing: "0.03em",
  },
  microservicePreviewList: {
    display: "grid",
    gap: 8,
  },
  microservicePreviewListItem: {
    fontSize: 13,
    lineHeight: 1.6,
    color: "#475569",
  },
  microservicePreviewEmpty: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "#94a3b8",
    fontStyle: "italic",
  },
  microservicePreviewHint: {
    fontSize: 11,
    color: "#64748b",
    lineHeight: 1.45,
  },
  microserviceRecommendationValue: {
    fontSize: 24,
    fontWeight: 800,
    color: "#7c2d12",
    lineHeight: 1.15,
  },
  microserviceScoreHighlight: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 12,
    background: "rgba(255,255,255,0.88)",
    border: "1px solid #dbeafe",
    color: "#1e3a8a",
    fontSize: 13,
  },
  microserviceAccordionCard: {
    border: "1px solid #e2e8f0",
    borderRadius: 18,
    padding: 16,
    boxShadow: "0 10px 24px rgba(15, 23, 42, 0.04)",
  },
  microserviceAccordionToggle: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 14,
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
    fontFamily: "inherit",
  },
  microserviceAccordionContentBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    flex: 1,
    minWidth: 220,
  },
  microserviceAccordionTitle: {
    fontSize: 17,
    fontWeight: 800,
    lineHeight: 1.2,
  },
  microserviceAccordionSubtitle: {
    fontSize: 13,
    lineHeight: 1.6,
  },
  microserviceAccordionMeta: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 10,
    flexWrap: "wrap",
  },
  microserviceAccordionMetaPill: {
    display: "inline-flex",
    alignItems: "center",
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: 999,
    padding: "7px 10px",
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.03em",
  },
  microserviceAccordionChevron: {
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  microserviceAccordionBody: {
    marginTop: 16,
  },
  microserviceAccordionSectionGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: 12,
  },
  microserviceInsightCard: {
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minHeight: 100,
  },
  microserviceInsightTitle: {
    fontSize: 14,
    fontWeight: 800,
    color: "#1e293b",
  },
  microserviceInsightText: {
    fontSize: 13,
    color: "#334155",
    lineHeight: 1.7,
  },
  microserviceEvidenceSubtitle: {
    fontSize: 12,
    color: "#64748b",
    lineHeight: 1.55,
  },
  microserviceBulletItem: {
    fontSize: 13,
    color: "#334155",
    lineHeight: 1.6,
  },
  microserviceEvidenceFooter: {
    marginTop: 8,
    display: "flex",
    justifyContent: "flex-start",
  },
  microserviceEvidenceToggle: {
    border: "1px solid #cbd5e1",
    background: "#ffffff",
    color: "#1d4ed8",
    borderRadius: 999,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  microserviceScoreBreakdownList: {
    display: "grid",
    gap: 12,
  },
  microserviceScoreCard: {
    background: "#ffffff",
    border: "1px solid #dbeafe",
    borderRadius: 16,
    padding: 16,
    boxShadow: "0 8px 18px rgba(15, 23, 42, 0.04)",
  },
  microserviceScoreHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 10,
  },
  microserviceScoreName: {
    fontSize: 14,
    fontWeight: 700,
    color: "#1e293b",
  },
  microserviceScoreTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  microserviceScoreInfoButton: {
    width: 20,
    height: 20,
    borderRadius: "50%",
    border: "1px solid #93c5fd",
    background: "#eff6ff",
    color: "#1d4ed8",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 800,
    cursor: "pointer",
    padding: 0,
    lineHeight: 1,
  },
  microserviceScoreWeight: {
    fontSize: 11,
    color: "#64748b",
    marginTop: 2,
  },
  microserviceScoreValue: {
    fontSize: 16,
    fontWeight: 800,
    color: "#0f172a",
  },
  microserviceScoreTrack: {
    width: "100%",
    height: 8,
    borderRadius: 999,
    background: "#e2e8f0",
    overflow: "hidden",
    marginBottom: 8,
  },
  microserviceScoreFill: {
    height: "100%",
    borderRadius: 999,
  },
  microserviceScoreText: {
    fontSize: 12,
    color: "#475569",
    lineHeight: 1.6,
  },
  microserviceScoreEvidenceBox: {
    marginTop: 12,
    padding: "12px 14px",
    borderRadius: 14,
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    display: "grid",
    gap: 6,
  },
  microserviceScoreEvidenceTitle: {
    fontSize: 12,
    fontWeight: 800,
    color: "#334155",
  },
  microserviceScoreEvidenceItem: {
    fontSize: 12,
    color: "#475569",
    lineHeight: 1.6,
  },
  microserviceScoreTooltip: {
    marginBottom: 10,
    padding: "12px 14px",
    borderRadius: 14,
    background: "#eff6ff",
    border: "1px solid #bfdbfe",
    display: "grid",
    gap: 6,
  },
  microserviceScoreTooltipTitle: {
    fontSize: 12,
    fontWeight: 800,
    color: "#1e3a8a",
    lineHeight: 1.5,
  },
  microserviceScoreTooltipText: {
    fontSize: 12,
    color: "#334155",
    lineHeight: 1.6,
  },
  microserviceServiceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 12,
  },
  microserviceServiceCard: {
    background: "#ffffff",
    border: "1px solid #dbeafe",
    borderRadius: 16,
    padding: 16,
    boxShadow: "0 8px 18px rgba(15, 23, 42, 0.04)",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  microserviceServiceHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
  },
  microserviceServiceTitle: {
    fontSize: 15,
    fontWeight: 800,
    color: "#1d4ed8",
    lineHeight: 1.3,
  },
  microserviceTransactionalBadge: {
    flexShrink: 0,
    fontSize: 10,
    fontWeight: 800,
    color: "#92400e",
    background: "#fef3c7",
    border: "1px solid #fcd34d",
    borderRadius: 999,
    padding: "4px 8px",
  },
  microserviceServicePackages: {
    fontSize: 12,
    color: "#475569",
    lineHeight: 1.55,
  },
  microserviceServiceEvidence: {
    display: "grid",
    gap: 6,
  },
  microserviceServiceSignalsLabel: {
    fontSize: 11,
    fontWeight: 800,
    color: "#64748b",
    letterSpacing: "0.03em",
    textTransform: "uppercase",
  },
  microserviceTagRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  microserviceTagButton: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 8px",
    borderRadius: 999,
    background: "#ccfbf1",
    border: "1px solid #99f6e4",
    color: "#0f766e",
    fontSize: 10,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  microserviceTag: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 8px",
    borderRadius: 999,
    background: "#ccfbf1",
    border: "1px solid #99f6e4",
    color: "#0f766e",
    fontSize: 10,
    fontWeight: 700,
  },
  microserviceTagMutedButton: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 8px",
    borderRadius: 999,
    background: "#f1f5f9",
    border: "1px solid #cbd5e1",
    color: "#475569",
    fontSize: 10,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  microserviceTagMuted: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 8px",
    borderRadius: 999,
    background: "#f1f5f9",
    border: "1px solid #cbd5e1",
    color: "#475569",
    fontSize: 10,
    fontWeight: 700,
  },
  microserviceServiceTagTooltip: {
    marginTop: 10,
    padding: "12px 14px",
    borderRadius: 14,
    background: "#f8fafc",
    border: "1px solid #dbeafe",
    display: "grid",
    gap: 6,
  },
  microserviceServiceTagTooltipTitle: {
    fontSize: 12,
    fontWeight: 800,
    color: "#1e3a8a",
    lineHeight: 1.5,
  },
  microserviceServiceTagTooltipText: {
    fontSize: 12,
    color: "#334155",
    lineHeight: 1.6,
  },
  microserviceDecisionGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: 12,
  },
  microserviceDecisionCard: {
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    boxShadow: "0 8px 18px rgba(15, 23, 42, 0.04)",
  },
  microserviceDecisionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
  },
  microserviceDecisionTitle: {
    fontSize: 15,
    fontWeight: 800,
    color: "#1e293b",
    lineHeight: 1.35,
  },
  microserviceDecisionBadge: {
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 8px",
    borderRadius: 999,
    background: "#ffffff",
    border: "1px solid #cbd5e1",
    color: "#0f172a",
    fontSize: 10,
    fontWeight: 800,
    letterSpacing: "0.03em",
  },
  microserviceDecisionLead: {
    fontSize: 13,
    color: "#475569",
    lineHeight: 1.65,
  },
  microserviceDecisionList: {
    display: "grid",
    gap: 6,
  },
  microserviceDecisionItem: {
    fontSize: 13,
    color: "#166534",
    lineHeight: 1.6,
  },
  microserviceDetailedGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 12,
  },
  microserviceDetailedCard: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 16,
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    boxShadow: "0 8px 18px rgba(15, 23, 42, 0.04)",
  },
  microserviceDetailedTitle: {
    fontSize: 13,
    fontWeight: 800,
    color: "#1e293b",
  },
  microserviceDetailedItem: {
    fontSize: 12,
    color: "#475569",
    lineHeight: 1.6,
  },
  microserviceDetailedEmpty: {
    fontSize: 12,
    color: "#94a3b8",
    fontStyle: "italic",
  },
  microserviceEmptyState: {
    border: "1px dashed #cbd5e1",
    borderRadius: 14,
    padding: 18,
    textAlign: "center",
    background: "#ffffff",
    color: "#64748b",
    fontSize: 13,
    lineHeight: 1.6,
  },
  radioGroup: { display: "flex", flexDirection: "column", gap: 10 },
  radioLabel: { display: "flex", alignItems: "flex-start", gap: 12, padding: 16, border: "1px solid #e2e8f0", borderRadius: 10, cursor: "pointer", transition: "all 0.2s ease", backgroundColor: "#fff" },
  radio: { marginTop: 4, accentColor: "#2563eb" },
  checkbox: { width: 18, height: 18, accentColor: "#2563eb", cursor: "pointer" },
  frameworkGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 14 },
  frameworkItem: { display: "flex", alignItems: "center", gap: 12, padding: 16, border: "1px solid #e2e8f0", borderRadius: 10, cursor: "pointer", background: "#fff", transition: "all 0.2s ease" },
  detectedBadge: { marginLeft: "auto", fontSize: 11, padding: "4px 10px", background: "#059669", color: "#fff", borderRadius: 12, fontWeight: 600 },
  conversionGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14 },
  conversionItem: { display: "flex", alignItems: "flex-start", gap: 14, padding: 18, border: "1px solid #e2e8f0", borderRadius: 10, cursor: "pointer", position: "relative", transition: "all 0.2s ease", background: "#fff" },
  conversionIcon: { fontSize: 24 },
  checkMark: { position: "absolute", top: 10, right: 10, color: "#059669", fontWeight: 700, fontSize: 18 },
  optionsGrid: { display: "flex", flexDirection: "column", gap: 14 },
  optionItem: { display: "flex", alignItems: "flex-start", gap: 14, padding: 18, border: "1px solid #e2e8f0", borderRadius: 10, cursor: "pointer", background: "#fff", transition: "all 0.2s ease" },
  progressSection: { marginBottom: 24 },
  progressHeader: { display: "flex", justifyContent: "space-between", marginBottom: 10, fontSize: 14, fontWeight: 600, color: "#1e293b" },
  progressBar: { width: "100%", height: 10, background: "#e5e7eb", borderRadius: 6, overflow: "hidden" },
  progressFill: { height: "100%", background: "#2563eb", borderRadius: 6, transition: "width 0.4s ease" },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 16, marginBottom: 24 },
  statBox: { background: "#fff", padding: 20, borderRadius: 10, textAlign: "center", border: "1px solid #e2e8f0" },
  statValue: { fontSize: 28, fontWeight: 700, color: "#2563eb" },
  statLabel: { fontSize: 12, color: "#64748b", marginTop: 8, fontWeight: 600, textTransform: "uppercase" },
  successBox: { background: "#dcfce7", border: "1px solid #86efac", borderRadius: 12, padding: 28, textAlign: "center", marginBottom: 24 },
  successTitle: { fontSize: 20, fontWeight: 700, color: "#166534", marginBottom: 12 },
  repoLink: { display: "inline-block", color: "#2563eb", fontWeight: 600, textDecoration: "none", fontSize: 14, padding: "10px 20px", background: "#eff6ff", borderRadius: 8 },
  connectionModes: { display: "flex", gap: 14, marginBottom: 20 },
  modeButton: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 8, padding: 20, border: "1px solid #e2e8f0", borderRadius: 10, background: "#fff", cursor: "pointer", transition: "all 0.2s ease", fontWeight: 500 },
  modeButtonActive: { border: "1px solid #2563eb", background: "#eff6ff" },
  modeIcon: { fontSize: 28 },
  modeTitle: { fontWeight: 600, fontSize: 14 },
  modeDesc: { fontSize: 12, color: "#64748b", textAlign: "center", lineHeight: 1.4 },
  fileList: { display: "flex", flexDirection: "column", gap: 8, maxHeight: 380, overflowY: "auto", border: "1px solid #e2e8f0", borderRadius: 10, padding: 14, background: "#f8fafc" },
  breadcrumb: { display: "flex", alignItems: "center", gap: 12, marginBottom: 14, padding: "10px 14px", background: "#eff6ff", borderRadius: 8, border: "1px solid #bfdbfe" },
  backBtn: { background: "none", border: "none", color: "#2563eb", cursor: "pointer", fontSize: 14, fontWeight: 600 },
  fileItem: { display: "flex", alignItems: "center", gap: 12, padding: "14px 16px", border: "1px solid #e2e8f0", borderRadius: 8, cursor: "pointer", transition: "all 0.2s ease", backgroundColor: "#fff" },
  fileIcon: { fontSize: 20 },
  fileInfo: { flex: 1 },
  fileName: { fontWeight: 600, fontSize: 14, color: "#1e293b" },
  filePath: { fontSize: 12, color: "#64748b", marginTop: 2 },
  fileSize: { fontSize: 11, color: "#94a3b8", fontWeight: 500, padding: "3px 8px", backgroundColor: "#f1f5f9", borderRadius: 6 },
  discoveryContent: { display: "flex", flexDirection: "column", gap: 14 },
  discoveryItem: { display: "flex", alignItems: "center", gap: 14, padding: 18, background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  discoveryIcon: { fontSize: 26 },
  discoveryTitle: { fontSize: 15, fontWeight: 600, color: "#1e293b", marginBottom: 2 },
  discoveryDesc: { fontSize: 13, color: "#64748b" },
  documentCard: { background: "#ffffff", border: "1px solid #dbe5f3", borderRadius: 14, padding: 20, marginBottom: 24, boxShadow: "0 8px 24px rgba(15, 23, 42, 0.04)" },
  documentCardHeader: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 16 },
  documentCardTitleRow: { display: "flex", alignItems: "center", gap: 10 },
  documentCardIcon: { fontSize: 16, lineHeight: 1 },
  documentCardTitle: { fontSize: 17, fontWeight: 700, color: "#1e293b" },
  documentCardSubtitle: { fontSize: 14, color: "#64748b", lineHeight: 1.6, maxWidth: 880 },
  documentActionRow: { display: "flex", gap: 12, flexWrap: "wrap", marginBottom: 12 },
  documentHelperText: { fontSize: 12, color: "#94a3b8", lineHeight: 1.5 },
  detectedConfigCard: { background: "linear-gradient(135deg, #eff6ff 0%, #f8fafc 100%)", border: "1px solid #bfdbfe", borderRadius: 12, padding: 20, marginTop: 18, marginBottom: 20 },
  detectedConfigHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, marginBottom: 14 },
  detectedConfigTitle: { fontSize: 16, fontWeight: 700, color: "#1e3a8a", marginBottom: 4 },
  detectedConfigSubtitle: { fontSize: 13, color: "#475569", lineHeight: 1.5 },
  detectedConfigActions: { display: "flex", flexWrap: "wrap", gap: 12, marginBottom: 12 },
  detectedConfigChip: { padding: "10px 14px", borderRadius: 999, border: "1px solid #93c5fd", background: "#fff", color: "#1e3a8a", fontSize: 13, fontWeight: 600, cursor: "default" },
  detectedConfigActionBtn: { padding: "10px 16px", borderRadius: 999, border: "1px solid #2563eb", background: "#2563eb", color: "#fff", fontSize: 13, fontWeight: 700, cursor: "pointer", transition: "all 0.2s ease" },
  detectedConfigActionBtnActive: { background: "#1d4ed8", borderColor: "#1d4ed8", boxShadow: "0 0 0 3px rgba(37, 99, 235, 0.15)" },
  detectedConfigNote: { fontSize: 12, color: "#475569", lineHeight: 1.5 },
  reportContainer: { display: "flex", flexDirection: "column", gap: 22 },
  reportHeroShell: {
    borderRadius: 28,
    padding: 28,
    background: "linear-gradient(180deg, #ffffff 0%, #fcfdff 58%, #f8fbff 100%)",
    border: "1px solid #dbeafe",
    boxShadow: "0 24px 52px rgba(37, 99, 235, 0.10)",
  },
  reportHeroHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 20, flexWrap: "wrap", marginBottom: 22 },
  reportHeroContent: { display: "flex", flexDirection: "column", gap: 12, flex: 1, minWidth: 280 },
  reportHeroBadgeRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  reportHeroEyebrow: { fontSize: 11, fontWeight: 800, letterSpacing: "0.14em", textTransform: "uppercase", color: "#2563eb" },
  reportHeroFeatureBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    padding: "7px 12px",
    background: "linear-gradient(180deg, #faf5ff 0%, #f3e8ff 100%)",
    border: "1px solid #e9d5ff",
    color: "#7c3aed",
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.02em",
    boxShadow: "0 10px 22px rgba(124, 58, 237, 0.10)",
  },
  reportHeroTitleRow: { display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" },
  reportHeroTitle: { margin: 0, fontSize: 30, lineHeight: 1.08, fontWeight: 800, color: "#0f172a" },
  reportHeroSubtitle: { margin: 0, fontSize: 14, lineHeight: 1.7, color: "#475569", maxWidth: 720 },
  reportHeroStatusPill: { display: "inline-flex", alignItems: "center", justifyContent: "center", borderRadius: 999, borderWidth: 1, borderStyle: "solid", padding: "8px 13px", fontSize: 12, fontWeight: 800, whiteSpace: "nowrap", boxShadow: "0 10px 22px rgba(15, 23, 42, 0.05)" },
  reportHeroAside: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 12, minWidth: 240, flexShrink: 0 },
  reportHeroElapsed: { display: "inline-flex", alignItems: "center", gap: 8, padding: "8px 12px", borderRadius: 999, background: "#ffffff", border: "1px solid #e2e8f0", color: "#0f172a", fontSize: 13, fontWeight: 800, boxShadow: "0 8px 18px rgba(15, 23, 42, 0.04)" },
  reportHeroElapsedLabel: { fontSize: 11, color: "#64748b", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.06em", marginRight: 8 },
  reportHeroElapsedValue: { display: "inline-flex", alignItems: "center", gap: 8, fontSize: 14, fontWeight: 800, color: "#0f172a" },
  reportHeroMiniMeta: { display: "flex", flexWrap: "wrap", gap: 10, justifyContent: "flex-end" },
  reportHeroMetaPill: { display: "inline-flex", alignItems: "center", justifyContent: "center", borderRadius: 999, padding: "9px 13px", background: "#ffffff", border: "1px solid #dbeafe", color: "#334155", fontSize: 12, fontWeight: 700, boxShadow: "0 10px 22px rgba(15, 23, 42, 0.05)" },
  reportHeroStatsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 16 },
  reportHeroStatCard: { background: "rgba(255,255,255,0.92)", border: "1px solid #e2e8f0", borderRadius: 22, padding: "22px 20px 20px", minHeight: 144, display: "flex", flexDirection: "column", justifyContent: "center", boxShadow: "0 16px 30px rgba(15, 23, 42, 0.05)" },
  reportHeroStatValue: { fontSize: 40, lineHeight: 1, fontWeight: 800, marginBottom: 12 },
  reportHeroStatLabel: { fontSize: 11, color: "#64748b", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.10em" },
  reportHeroStatMeta: { fontSize: 12, color: "#64748b", marginTop: 10, lineHeight: 1.5, fontWeight: 600 },
  reportSection: { background: "linear-gradient(180deg, #ffffff 0%, #fbfdff 100%)", borderRadius: 20, padding: 24, border: "1px solid #e2e8f0", boxShadow: "0 16px 36px rgba(15, 23, 42, 0.05)" },
  reportAccordionToggle: {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    background: "transparent",
    border: "none",
    padding: 0,
    marginBottom: 18,
    textAlign: "left",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  reportAccordionIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 36,
    height: 36,
    borderRadius: 12,
    background: "#eff6ff",
    color: "#1d4ed8",
    fontSize: 18,
    fontWeight: 800,
    flexShrink: 0,
  },
  reportAccordionSubtitle: { fontSize: 13, color: "#64748b", lineHeight: 1.6 },
  reportTitle: { fontSize: 18, fontWeight: 800, color: "#0f172a", marginBottom: 18, paddingBottom: 14, borderBottom: "1px solid #e2e8f0", display: "flex", alignItems: "center", gap: 10 },
  reportGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16 },
  reportItem: { display: "flex", flexDirection: "column", gap: 8, padding: 16, borderRadius: 16, background: "rgba(255,255,255,0.9)", border: "1px solid #e2e8f0" },
  reportLabel: { fontSize: 11, color: "#64748b", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em" },
  reportValue: { fontSize: 14, color: "#0f172a", fontWeight: 700, lineHeight: 1.6, wordBreak: "break-word" },
  testResults: { display: "flex", flexDirection: "column", gap: 10 },
  testItem: { display: "flex", justifyContent: "space-between", padding: "14px 18px", background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  sonarqubeResults: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 16 },
  qualityItem: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "16px 18px", background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  logsContainer: { background: "linear-gradient(180deg, #1e293b 0%, #172033 100%)", color: "#86efac", fontFamily: "'JetBrains Mono', 'Fira Code', monospace", padding: 20, borderRadius: 16, maxHeight: 340, overflowY: "auto", fontSize: 12, lineHeight: 1.75, border: "1px solid #334155", boxShadow: "inset 0 1px 0 rgba(255,255,255,0.03)" },
  logEntry: { marginBottom: 8, padding: "6px 0", borderBottom: "1px solid rgba(148,163,184,0.14)" },
  issuesContainer: { display: "flex", flexDirection: "column", gap: 14 },
  issueItem: { padding: 18, background: "linear-gradient(180deg, #ffffff 0%, #fafcff 100%)", borderRadius: 16, border: "1px solid #dbe5f3", boxShadow: "0 10px 24px rgba(15, 23, 42, 0.04)" },
  issueHeader: { display: "flex", alignItems: "center", gap: 10, marginBottom: 12, flexWrap: "wrap" },
  issueSeverity: { padding: "6px 12px", borderRadius: 999, fontSize: 10, fontWeight: 800, color: "#fff", textTransform: "uppercase", letterSpacing: "0.08em" },
  issueCategory: { fontSize: 11, color: "#64748b", fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.08em" },
  issueStatus: { fontSize: 11, color: "#059669", fontWeight: 800, marginLeft: "auto", textTransform: "uppercase", letterSpacing: "0.08em" },
  issueMessage: { fontSize: 14, color: "#0f172a", marginBottom: 10, fontWeight: 600, lineHeight: 1.55 },
  issueFile: { fontSize: 12, color: "#2563eb", fontFamily: "'JetBrains Mono', monospace", backgroundColor: "#eff6ff", padding: "8px 12px", borderRadius: 10, display: "inline-block", border: "1px solid #dbeafe" },
  noIssues: { textAlign: "center", color: "#64748b", padding: 28, fontStyle: "italic", fontSize: 14 },
  noFilesMsg: { textAlign: "center", color: "#64748b", padding: 28, fontStyle: "italic", background: "#f8fafc", borderRadius: 10, border: "1px dashed #e2e8f0" },
  noLogs: { textAlign: "center", color: "#64748b", padding: 28, fontStyle: "italic" },

  // Animation styles
  animationContainer: {
    padding: 28,
    background: "linear-gradient(180deg, #fbfdff 0%, #f6f9ff 55%, #f8fafc 100%)",
    borderRadius: 28,
    marginTop: 20,
    border: "1px solid #dbe5f3",
    boxShadow: "0 24px 60px rgba(37, 99, 235, 0.06)",
  },
  migrationAnimation: { maxWidth: 760, margin: "0 auto" },
  animationHeader: { textAlign: "center", marginBottom: 34 },
  migratingText: { fontSize: 34, fontWeight: 800, color: "#0f172a", marginBottom: 14, letterSpacing: "-0.03em", lineHeight: 1.08 },
  versionTransition: {
    fontSize: 14,
    color: "#eff6ff",
    padding: "12px 20px",
    background: "linear-gradient(135deg, #2563eb 0%, #4f46e5 55%, #7c3aed 100%)",
    borderRadius: 999,
    display: "inline-block",
    fontWeight: 700,
    boxShadow: "0 16px 34px rgba(79, 70, 229, 0.18)",
  },
  animationSteps: { display: "flex", flexDirection: "column", gap: 16, marginBottom: 30 },
  animationStep: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "18px 20px",
    background: "rgba(255,255,255,0.86)",
    borderRadius: 18,
    border: "1px solid rgba(219, 229, 243, 0.95)",
    boxShadow: "0 12px 28px rgba(15, 23, 42, 0.04)",
    backdropFilter: "blur(8px)",
  },
  stepIconAnimated: { fontSize: 22, minWidth: 22 },
  stepText: { flex: 1, fontSize: 14, fontWeight: 600, color: "#1e293b" },
  checkMarkAnimated: { fontSize: 18, color: "#059669" },
  progressExperienceSection: {
    marginTop: 6,
    display: "flex",
    flexDirection: "column",
    gap: 22,
    padding: "8px 0 4px",
  },
  animatedProgressSection: {
    marginBottom: 0,
    padding: 0,
    borderRadius: 0,
    background: "transparent",
    border: "none",
  },
  animatedProgressHeader: { display: "flex", justifyContent: "space-between", marginBottom: 12, fontSize: 13, fontWeight: 800, color: "#0f172a", textTransform: "uppercase", letterSpacing: "0.04em" },
  animatedProgressBar: { width: "100%", height: 8, background: "#dbe4f0", borderRadius: 999, overflow: "hidden", boxShadow: "inset 0 1px 2px rgba(15, 23, 42, 0.08)" },
  animatedProgressFill: { height: "100%", borderRadius: 999, transition: "width 0.4s ease", background: "#2563eb" },
  progressInsightRow: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    width: "min(100%, 560px)",
    margin: "0 auto",
  },
  statusHeroBlock: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 0,
    minHeight: 0,
    maxWidth: "100%",
    textAlign: "center",
  },
  currentStatusHeadline: {
    fontSize: 22,
    fontWeight: 800,
    color: "#0f172a",
    lineHeight: 1.25,
  },
  recentLog: {
    fontSize: 13,
    color: "#64748b",
    fontFamily: "'JetBrains Mono', monospace",
    background: "rgba(255,255,255,0.78)",
    padding: "12px 16px",
    borderRadius: 14,
    border: "1px solid #dbe5f3",
    boxShadow: "0 10px 22px rgba(15, 23, 42, 0.04)",
  },

  // Report styles
  changesGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16 },
  changeItem: { display: "flex", alignItems: "center", gap: 16, padding: 20, background: "linear-gradient(180deg, #ffffff 0%, #f8fbff 100%)", borderRadius: 18, border: "1px solid #dbeafe", boxShadow: "0 14px 28px rgba(37, 99, 235, 0.06)" },
  changeIcon: { fontSize: 28, width: 48, height: 48, borderRadius: 14, display: "inline-flex", alignItems: "center", justifyContent: "center", background: "#eff6ff" },
  changeTitle: { fontSize: 15, fontWeight: 700, color: "#0f172a", marginBottom: 6 },
  changeValue: { fontSize: 13, color: "#475569", lineHeight: 1.6 },
  reportPagerBar: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap", marginBottom: 16, padding: "12px 14px", borderRadius: 14, background: "#f8fafc", border: "1px solid #e2e8f0" },
  reportPagerHint: { fontSize: 13, color: "#475569", fontWeight: 600 },
  reportPagerActions: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  reportPagerPage: { fontSize: 12, color: "#64748b", fontWeight: 700, minWidth: 90, textAlign: "center" },
  dependenciesReport: { display: "flex", flexDirection: "column", gap: 10 },
  dependencyReportItem: { display: "grid", gridTemplateColumns: "1fr 220px 150px", gap: 16, alignItems: "center", padding: "16px 18px", background: "rgba(255,255,255,0.92)", borderRadius: 16, border: "1px solid #e2e8f0", boxShadow: "0 8px 18px rgba(15, 23, 42, 0.03)" },
  dependencyName: { fontSize: 14, fontWeight: 700, color: "#0f172a", fontFamily: "'JetBrains Mono', monospace", wordBreak: "break-word", lineHeight: 1.55 },
  dependencyChange: { fontSize: 13, color: "#64748b", textAlign: "center", fontWeight: 600 },
  dependencyStatus: { padding: "7px 12px", borderRadius: 999, fontSize: 10, fontWeight: 800, textTransform: "uppercase", textAlign: "center", letterSpacing: "0.08em" },
  noData: { textAlign: "center", color: "#64748b", padding: 28, fontStyle: "italic" },
  errorsSummary: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 14 },
  errorStat: { textAlign: "center", padding: 18, background: "#fff", borderRadius: 10, border: "1px solid #e2e8f0" },
  errorCount: { display: "block", fontSize: 26, fontWeight: 700, color: "#1e293b", marginBottom: 6 },
  errorLabel: { fontSize: 12, color: "#64748b", fontWeight: 600, textTransform: "uppercase" },
  businessLogicGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 16 },
  businessItem: { display: "flex", alignItems: "flex-start", gap: 14, padding: 20, background: "linear-gradient(180deg, #ffffff 0%, #fffaf5 100%)", borderRadius: 18, border: "1px solid #fde7cf", boxShadow: "0 14px 28px rgba(249, 115, 22, 0.05)" },
  businessIcon: { fontSize: 24, marginTop: 2, width: 40, height: 40, borderRadius: 12, display: "inline-flex", alignItems: "center", justifyContent: "center", background: "#fff7ed" },
  businessTitle: { fontSize: 15, fontWeight: 700, color: "#0f172a", marginBottom: 6 },
  businessDesc: { fontSize: 13, color: "#475569", lineHeight: 1.6 },
  sonarSectionShell: { background: "linear-gradient(180deg, #ffffff 0%, #fbfdff 100%)", borderRadius: 18, boxShadow: "0 12px 40px rgba(15, 23, 42, 0.05)" },
  sonarSectionHeader: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginBottom: 14 },
  sonarSectionSubtitle: { fontSize: 13, color: "#64748b", lineHeight: 1.6, marginTop: -4 },
  sonarActionRow: { display: "flex", flexWrap: "wrap", gap: 10, marginBottom: 18 },
  sonarHeroPanel: { border: "1px solid #e0ecff", background: "linear-gradient(135deg, #f8fbff 0%, #ffffff 58%)", borderRadius: 18, padding: 18, marginBottom: 18 },
  sonarHeroHeader: { display: "flex", justifyContent: "space-between", alignItems: "stretch", gap: 18, flexWrap: "wrap" },
  sonarHeroEyebrow: { fontSize: 11, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase", color: "#2563eb", marginBottom: 8 },
  sonarHeroTitle: { fontSize: 24, fontWeight: 800, color: "#0f172a", lineHeight: 1.3, marginBottom: 10 },
  sonarHeroSubtitle: { fontSize: 13, color: "#475569", lineHeight: 1.7, maxWidth: 720 },
  sonarHeroMetaGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 14, minWidth: "min(100%, 360px)", flex: "0 0 360px" },
  sonarHeroMiniCard: { background: "#fff", border: "1px solid #dbeafe", borderRadius: 16, padding: 16, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 12, boxShadow: "0 12px 28px rgba(37, 99, 235, 0.08)" },
  sonarHeroMiniLabel: { fontSize: 11, fontWeight: 800, letterSpacing: "0.08em", textTransform: "uppercase", color: "#64748b" },
  sonarqubeGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 20, marginBottom: 20 },
  sonarqubeItem: { textAlign: "center" },
  qualityGate: { marginBottom: 18 },
  gateStatus: { display: "inline-block", padding: "12px 24px", borderRadius: 20, color: "#fff", fontSize: 14, fontWeight: 700, textTransform: "uppercase" },
  gateLabel: { display: "block", fontSize: 12, color: "#64748b", marginTop: 10, fontWeight: 600 },
  coverageMeter: { position: "relative" },
  coverageCircle: { width: 110, height: 110, borderRadius: "50%", background: "#eff6ff", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", margin: "0 auto", border: "3px solid #2563eb" },
  coveragePercent: { fontSize: 26, fontWeight: 700, color: "#2563eb" },
  coverageLabel: { fontSize: 11, color: "#64748b", fontWeight: 600, marginTop: 2 },
  qualityMetrics: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 14 },
  metricItem: { textAlign: "center", padding: 16, background: "#fff", borderRadius: 16, borderWidth: 1, borderStyle: "solid", borderColor: "#e2e8f0", cursor: "pointer", transition: "all 0.2s ease", minHeight: 126, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 6, width: "100%", appearance: "none", fontFamily: "inherit" },
  metricItemActive: { boxShadow: "0 0 0 2px rgba(37, 99, 235, 0.18)", borderColor: "#93c5fd", background: "#eff6ff" },
  metricValue: { display: "block", fontSize: 22, fontWeight: 700, marginBottom: 6, color: "#1e293b" },
  metricLabel: { fontSize: 11, color: "#64748b", fontWeight: 600, textTransform: "uppercase" },
  metricHelper: { fontSize: 12, color: "#64748b", lineHeight: 1.5 },
  sonarRiskSummaryGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 14, marginBottom: 18 },
  sonarRiskSummaryCard: { borderWidth: 1.5, borderStyle: "solid", borderRadius: 16, padding: "16px 18px", minHeight: 108, display: "flex", flexDirection: "column", justifyContent: "center", boxShadow: "0 10px 26px rgba(15, 23, 42, 0.04)" },
  sonarRiskSummaryLabel: { fontSize: 11, fontWeight: 800, letterSpacing: "0.08em", textTransform: "uppercase", color: "#64748b", marginBottom: 10 },
  sonarRiskSummaryValue: { fontSize: 30, fontWeight: 800, lineHeight: 1.1, color: "#0f172a" },
  sonarRecommendationPanel: { border: "1px solid #bfdbfe", background: "#eff6ff", borderRadius: 16, padding: "16px 18px", marginBottom: 18 },
  sonarRecommendationTitle: { fontSize: 14, fontWeight: 800, color: "#1d4ed8", marginBottom: 10 },
  sonarRecommendationList: { display: "flex", flexDirection: "column", gap: 8 },
  sonarRecommendationItem: { fontSize: 13, color: "#1e3a8a", lineHeight: 1.6 },
  sonarCategoryHeader: { marginBottom: 14 },
  sonarFindingsPanel: { marginTop: 6, display: "flex", flexDirection: "column", gap: 16, background: "#fff", border: "1px solid #e2e8f0", borderRadius: 18, padding: 18 },
  sonarFindingsPanelIntro: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 14, flexWrap: "wrap", padding: "4px 2px 2px" },
  sonarFindingsPanelEyebrow: { fontSize: 11, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase", color: "#2563eb", marginBottom: 6 },
  sonarFindingsPanelSummaryBadge: { display: "inline-flex", alignItems: "center", justifyContent: "center", padding: "10px 14px", borderRadius: 999, background: "linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%)", color: "#1d4ed8", fontSize: 12, fontWeight: 800, border: "1px solid #bfdbfe", whiteSpace: "nowrap" },
  sonarFindingsPanelHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" },
  sonarFindingsPanelTitle: { fontSize: 16, fontWeight: 700, color: "#1e293b", marginBottom: 4 },
  sonarFindingsPanelSubtitle: { fontSize: 13, color: "#64748b", lineHeight: 1.5 },
  sonarFilterBar: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap", padding: "10px 14px", borderRadius: 14, background: "#f8fafc", border: "1px solid #e2e8f0" },
  sonarFilterLabel: { fontSize: 13, color: "#334155", fontWeight: 700 },
  sonarFilterClearButton: { border: "1px solid #cbd5e1", background: "#fff", color: "#334155", borderRadius: 999, padding: "7px 12px", fontSize: 12, fontWeight: 700, cursor: "pointer", boxShadow: "0 4px 14px rgba(15, 23, 42, 0.06)" },
  sonarSeverityFilterRow: { display: "flex", flexWrap: "wrap", gap: 10, paddingTop: 2 },
  sonarSeverityFilterButton: { borderWidth: 1, borderStyle: "solid", borderColor: "#dbe5f3", background: "#fff", color: "#334155", borderRadius: 999, padding: "7px 12px", fontSize: 12, fontWeight: 700, cursor: "pointer" },
  sonarSeverityFilterButtonActive: { background: "#eff6ff", color: "#1d4ed8", borderColor: "#93c5fd" },
  sonarCategoryCardGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14 },
  sonarCategoryCard: { width: "100%", appearance: "none", fontFamily: "inherit", textAlign: "left", borderWidth: 1, borderStyle: "solid", borderRadius: 18, padding: 18, minHeight: 150, cursor: "pointer", transition: "all 0.2s ease", display: "flex", flexDirection: "column", justifyContent: "space-between" },
  sonarCategoryCardTopRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12 },
  sonarCategoryIconBadge: { width: 40, height: 40, borderRadius: 12, display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 800, borderWidth: 1, borderStyle: "solid" },
  sonarCategoryStatusBadge: { display: "inline-flex", alignItems: "center", justifyContent: "center", borderRadius: 999, padding: "6px 10px", fontSize: 10, fontWeight: 800, letterSpacing: "0.08em" },
  sonarCategoryCardValue: { fontSize: 40, lineHeight: 1, fontWeight: 800, marginTop: 18 },
  sonarCategoryCardLabel: { fontSize: 12, fontWeight: 800, color: "#475569", letterSpacing: "0.08em", textTransform: "uppercase", marginTop: 8 },
  sonarCategoryCardNote: { fontSize: 13, color: "#64748b", lineHeight: 1.5, marginTop: 8 },
  sonarFindingSection: { background: "#fff", borderWidth: 1, borderStyle: "solid", borderColor: "#e2e8f0", borderRadius: 16, padding: 16, boxShadow: "0 10px 24px rgba(15, 23, 42, 0.04)" },
  sonarFindingSectionHeader: { marginBottom: 12 },
  sonarFindingSectionTitleRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap" },
  sonarFindingSectionTitle: { margin: 0, fontSize: 15, fontWeight: 700, color: "#1e293b" },
  sonarFindingSectionDescription: { fontSize: 12, color: "#64748b", lineHeight: 1.6, marginTop: 6 },
  sonarFindingCountBadge: { display: "inline-flex", alignItems: "center", justifyContent: "center", minWidth: 40, padding: "6px 10px", borderRadius: 999, borderWidth: 1, borderStyle: "solid", fontSize: 12, fontWeight: 800 },
  sonarFindingsList: { display: "flex", flexDirection: "column", gap: 12, maxHeight: 540, overflowY: "auto", paddingRight: 4 },
  sonarFindingCard: { borderWidth: 1, borderStyle: "solid", borderColor: "#e2e8f0", borderRadius: 14, padding: 14, background: "rgba(255,255,255,0.92)" },
  sonarFindingHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 10, flexWrap: "wrap" },
  sonarFindingTitle: { fontSize: 14, fontWeight: 700, color: "#1e293b", lineHeight: 1.5, flex: 1, minWidth: 240 },
  sonarFindingBadgeRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  sonarFindingBadge: { display: "inline-flex", alignItems: "center", borderRadius: 999, padding: "5px 9px", fontSize: 11, fontWeight: 800 },
  sonarFindingMeta: { display: "flex", flexWrap: "wrap", gap: 8, fontSize: 12, color: "#475569", lineHeight: 1.5 },
  sonarFindingMetaPill: { display: "inline-flex", alignItems: "center", gap: 4, padding: "4px 10px", borderRadius: 999, background: "#eff6ff", color: "#1d4ed8", fontWeight: 700 },
  sonarFindingLoadMoreRow: { display: "flex", justifyContent: "center", paddingTop: 12 },
  sonarFindingLoadMoreButton: { border: "1px solid #cbd5e1", background: "#fff", color: "#1d4ed8", borderRadius: 999, padding: "8px 14px", fontSize: 12, fontWeight: 700, cursor: "pointer" },
  sonarFindingNote: { fontSize: 12, color: "#64748b", paddingTop: 4 },
  sonarFindingEmpty: { border: "1px dashed #cbd5e1", borderRadius: 12, padding: 16, textAlign: "center", fontSize: 13, color: "#64748b", background: "#f8fafc" },
  testStatus: { display: "flex", alignItems: "center", gap: 12, padding: 16, background: "#dcfce7", borderRadius: 16, border: "1px solid #86efac", boxShadow: "0 10px 24px rgba(34, 197, 94, 0.08)" },
  testStatusIcon: { fontSize: 18 },
  testSummaryReport: { borderRadius: 18, overflow: "hidden", border: "1px solid #e2e8f0", background: "#fff", marginBottom: 18, boxShadow: "0 10px 24px rgba(15, 23, 42, 0.05)" },
  testSummaryReportHeader: { background: "linear-gradient(135deg, #6d5efc 0%, #7c3aed 100%)", padding: "16px 18px", color: "#fff", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, flexWrap: "wrap" },
  testSummaryReportTitle: { fontSize: 12, fontWeight: 800, letterSpacing: "0.16em", textTransform: "uppercase" },
  testSummaryReportSubtitle: { marginTop: 6, fontSize: 12, opacity: 0.9, fontWeight: 600 },
  testSummaryReportGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 14, padding: 16, background: "#f8fafc" },
  testSummaryReportCard: { background: "#fff", border: "1px solid #e2e8f0", borderRadius: 14, padding: 14, textAlign: "center" },
  testSummaryReportValue: { fontSize: 22, fontWeight: 900, color: "#0f172a", lineHeight: 1.1 },
  testSummaryReportLabel: { marginTop: 8, fontSize: 11, fontWeight: 800, letterSpacing: "0.08em", textTransform: "uppercase", color: "#64748b" },
  jmeterGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 16 },
  jmeterItem: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "18px 20px", background: "linear-gradient(180deg, #ffffff 0%, #f8fafc 100%)", borderRadius: 16, border: "1px solid #e2e8f0", boxShadow: "0 10px 22px rgba(15, 23, 42, 0.04)" },
  jmeterLabel: { fontSize: 13, color: "#64748b", fontWeight: 600 },
  jmeterValue: { fontSize: 18, fontWeight: 800, color: "#0f172a" },
};
